# Generated by Django 3.2.12 on 2023-12-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='time_stamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='category',
            field=models.CharField(blank=True, choices=[('Cloths', 'cloths'), ('Ferniture', 'Ferniture'), ('Book', 'Book'), ('Foods', 'Foods'), ('Electronics', 'Electronics')], max_length=50, null=True),
        ),
    ]
