# Generated by Django 3.2.12 on 2023-12-16 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_pro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='os_model',
            field=models.CharField(blank=True, choices=[('window_7', 'window_7'), ('window_10', 'window_10'), ('linux', 'linux'), ('ubuntu', 'ubuntu'), ('window_8', 'window_8')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='IP_address',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='MAC_address',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='computer_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='location',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='users_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
