# Generated by Django 3.2.12 on 2023-12-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_pro', '0002_auto_20231216_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='export_to_CSV',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='computer',
            name='os_model',
            field=models.CharField(blank=True, choices=[('window_10', 'window_10'), ('window_7', 'window_7'), ('window_8', 'window_8'), ('linux', 'linux'), ('ubuntu', 'ubuntu')], max_length=30, null=True),
        ),
    ]
