# Generated by Django 3.2.12 on 2023-12-19 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_pro', '0005_auto_20231217_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('profile', models.CharField(max_length=30)),
                ('co_password', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='computer',
            name='os_model',
            field=models.CharField(blank=True, choices=[('linux', 'linux'), ('ubuntu', 'ubuntu'), ('window_8', 'window_8'), ('window_10', 'window_10'), ('window_7', 'window_7')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='computerhistory',
            name='os_model',
            field=models.CharField(blank=True, choices=[('linux', 'linux'), ('ubuntu', 'ubuntu'), ('window_8', 'window_8'), ('window_10', 'window_10'), ('window_7', 'window_7')], max_length=30, null=True),
        ),
    ]
