# Generated by Django 3.2.12 on 2023-12-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_pro', '0006_auto_20231219_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='os_model',
            field=models.CharField(blank=True, choices=[('window_10', 'window_10'), ('ubuntu', 'ubuntu'), ('window_8', 'window_8'), ('window_7', 'window_7'), ('linux', 'linux')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='computerhistory',
            name='os_model',
            field=models.CharField(blank=True, choices=[('window_10', 'window_10'), ('ubuntu', 'ubuntu'), ('window_8', 'window_8'), ('window_7', 'window_7'), ('linux', 'linux')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='profile',
            field=models.ImageField(default='baba.jpg', upload_to='images/'),
        ),
    ]
