# Generated by Django 3.2.12 on 2023-12-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_pro', '0017_auto_20231223_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='os_model',
            field=models.CharField(blank=True, choices=[('window_7', 'window_7'), ('linux', 'linux'), ('ubuntu', 'ubuntu'), ('window_10', 'window_10'), ('window_8', 'window_8')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='computerhistory',
            name='os_model',
            field=models.CharField(blank=True, choices=[('window_7', 'window_7'), ('linux', 'linux'), ('ubuntu', 'ubuntu'), ('window_10', 'window_10'), ('window_8', 'window_8')], max_length=30, null=True),
        ),
    ]
